version: "3.9"

##########################
#### Common Variables ####
##########################
x-common-env: &common-env
  PUID: $PUID
  PGID: $PGID
  TZ: $TZ

x-common-base: &common-base
  restart: unless-stopped
  networks: media
  environment: *common-env

x-volumes:
  - &vol_data ${dataFolder}:/data
  - &vol_dl   ${downloadsFolder}:/data/download
  - &vol_rd   ${realdebridFolder}:/realdebrid:rslave
  - &vol_lib  ${libraryFolder}:/data/media

##########################
######## Networks ########
##########################
networks:
  media:

##########################
######## Services ########
##########################

services:
  radarr:
    <<: *common-base
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - *vol_data
      - *vol_rd
      - $configFolder/radarr:/config
  sonarr:
    <<: *common-base
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - *vol_data
      - *vol_rd
      - $configFolder/sonarr:/config
  prowlarr:
    <<: *common-base
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - "9696:9696"
    volumes:
      - $configFolder/prowlarr:/config
  zurg:
    <<: *common-base
    image: ghcr.io/debridmediamanager/zurg-testing:latest    
    container_name: zurg
    ports:
      - 9999:9999
    volumes:
      - $configFolder/zurg/config.yml:/app/config.yml
      - $configFolder/zurg/data:/app/data
  rclone:
    <<: *common-base
    image: rclone/rclone:latest
    container_name: rclone
    volumes:
      - /$realdebridFolder:/realdebrid:rshared # CHANGE /mnt/zurg WITH YOUR PREFERRED MOUNT PATH
      - $configFolder/rclone/rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"
  decypharr:
    <<: *common-base
    image: cy01/blackhole:latest
    container_name: decypharr
    ports:
      - "8282:8282"
    volumes:
      - *vol_dl
  plex:
    restart: unless-stopped
    network_mode: host
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment: 
      - *common_env
      - VERSION=docker
    volumes:
      - *vol_lib
      - *vol_rd
      - $configFolder/plex:/config
